#!/bin/bash

set -e

export TOPDIR=`pwd`
export PATH=`pegasus-config --bin`:$PATH

KEG_PATH=`which pegasus-keg`
KEG_CHKSUM=`sha256sum $KEG_PATH`

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./dax-gen.py $KEG_PATH $KEG_CHKSUM

# site catalog
cat >sites.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">
    <site handle="local">
        <directory  path="${TOPDIR}/LOCAL/shared-scratch" type="shared-scratch">
            <file-server  operation="all" url="file:///${TOPDIR}/LOCAL/shared-scratch" />
        </directory>
        <directory  path="${TOPDIR}/LOCAL/shared-storage" type="shared-storage">
            <file-server  operation="all" url="file:///${TOPDIR}/LOCAL/shared-storage" />
        </directory>
    </site>

    <site  handle="condor_pool">
        <profile namespace="pegasus" key="style" >condor</profile>
        <profile namespace="condor" key="universe" >vanilla</profile>
        <profile namespace="env" key="PEGASUS_TRANSFER_ERROR_RATE" >5</profile>
    </site>
</sitecatalog>
EOF

echo
echo
echo "Planning and submitting the workflow..."
pegasus-plan \
    --conf pegasus.conf \
    --dir workflow \
    --dax dax.xml \
    --sites condor_pool \
    --staging-site local \
    --output-site local \
    --submit


